//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.01.20 at 12:51:29 PM CET 
//


package net.service.flickr;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the net.service.flickr package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: net.service.flickr
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Rsp }
     * 
     */
    public Rsp createRsp() {
        return new Rsp();
    }

    /**
     * Create an instance of {@link net.service.flickr.User }
     * 
     */
    public net.service.flickr.User createUser() {
        return new net.service.flickr.User();
    }

    /**
     * Create an instance of {@link Auth }
     * 
     */
    public Auth createAuth() {
        return new Auth();
    }

    /**
     * Create an instance of {@link Photoid }
     * 
     */
    public Photoid createPhotoid() {
        return new Photoid();
    }

    /**
     * Create an instance of {@link Person }
     * 
     */
    public Person createPerson() {
        return new Person();
    }

    /**
     * Create an instance of {@link Frob }
     * 
     */
    public Frob createFrob() {
        return new Frob();
    }

    /**
     * Create an instance of {@link Person.Photos }
     * 
     */
    public Person.Photos createPersonPhotos() {
        return new Person.Photos();
    }

    /**
     * Create an instance of {@link Groups.Group }
     * 
     */
    public Groups.Group createGroupsGroup() {
        return new Groups.Group();
    }

    /**
     * Create an instance of {@link Groups }
     * 
     */
    public Groups createGroups() {
        return new Groups();
    }

    /**
     * Create an instance of {@link net.service.flickr.Photos }
     * 
     */
    public net.service.flickr.Photos createPhotos() {
        return new net.service.flickr.Photos();
    }

    /**
     * Create an instance of {@link Err }
     * 
     */
    public Err createErr() {
        return new Err();
    }

    /**
     * Create an instance of {@link Auth.User }
     * 
     */
    public Auth.User createAuthUser() {
        return new Auth.User();
    }

    /**
     * Create an instance of {@link Photo }
     * 
     */
    public Photo createPhoto() {
        return new Photo();
    }

}
