//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.01.20 at 12:51:29 PM CET 
//


package net.service.flickr;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="username" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="realname" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="mbox_sha1sum" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="location" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="photosurl" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="profileurl" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="photos">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="firstdate" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="firstdatetaken" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="count" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attribute name="nsid" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="ispro" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="iconserver" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="iconfarm" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "username",
    "realname",
    "mboxSha1Sum",
    "location",
    "photosurl",
    "profileurl",
    "photos"
})
@XmlRootElement(name = "person")
public class Person {

    @XmlElement(required = true)
    protected String username;
    @XmlElement(required = true)
    protected String realname;
    @XmlElement(name = "mbox_sha1sum", required = true)
    protected String mboxSha1Sum;
    @XmlElement(required = true)
    protected String location;
    @XmlElement(required = true)
    protected String photosurl;
    @XmlElement(required = true)
    protected String profileurl;
    @XmlElement(required = true)
    protected Person.Photos photos;
    @XmlAttribute
    protected String nsid;
    @XmlAttribute
    protected Integer ispro;
    @XmlAttribute
    protected String iconserver;
    @XmlAttribute
    protected String iconfarm;

    /**
     * Gets the value of the username property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUsername() {
        return username;
    }

    /**
     * Sets the value of the username property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUsername(String value) {
        this.username = value;
    }

    /**
     * Gets the value of the realname property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRealname() {
        return realname;
    }

    /**
     * Sets the value of the realname property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRealname(String value) {
        this.realname = value;
    }

    /**
     * Gets the value of the mboxSha1Sum property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMboxSha1Sum() {
        return mboxSha1Sum;
    }

    /**
     * Sets the value of the mboxSha1Sum property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMboxSha1Sum(String value) {
        this.mboxSha1Sum = value;
    }

    /**
     * Gets the value of the location property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLocation() {
        return location;
    }

    /**
     * Sets the value of the location property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLocation(String value) {
        this.location = value;
    }

    /**
     * Gets the value of the photosurl property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPhotosurl() {
        return photosurl;
    }

    /**
     * Sets the value of the photosurl property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPhotosurl(String value) {
        this.photosurl = value;
    }

    /**
     * Gets the value of the profileurl property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProfileurl() {
        return profileurl;
    }

    /**
     * Sets the value of the profileurl property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProfileurl(String value) {
        this.profileurl = value;
    }

    /**
     * Gets the value of the photos property.
     * 
     * @return
     *     possible object is
     *     {@link Person.Photos }
     *     
     */
    public Person.Photos getPhotos() {
        return photos;
    }

    /**
     * Sets the value of the photos property.
     * 
     * @param value
     *     allowed object is
     *     {@link Person.Photos }
     *     
     */
    public void setPhotos(Person.Photos value) {
        this.photos = value;
    }

    /**
     * Gets the value of the nsid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNsid() {
        return nsid;
    }

    /**
     * Sets the value of the nsid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNsid(String value) {
        this.nsid = value;
    }

    /**
     * Gets the value of the ispro property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getIspro() {
        return ispro;
    }

    /**
     * Sets the value of the ispro property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setIspro(Integer value) {
        this.ispro = value;
    }

    /**
     * Gets the value of the iconserver property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIconserver() {
        return iconserver;
    }

    /**
     * Sets the value of the iconserver property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIconserver(String value) {
        this.iconserver = value;
    }

    /**
     * Gets the value of the iconfarm property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIconfarm() {
        return iconfarm;
    }

    /**
     * Sets the value of the iconfarm property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIconfarm(String value) {
        this.iconfarm = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="firstdate" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="firstdatetaken" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="count" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "firstdate",
        "firstdatetaken",
        "count"
    })
    public static class Photos {

        @XmlElement(required = true)
        protected String firstdate;
        @XmlElement(required = true)
        protected String firstdatetaken;
        protected int count;

        /**
         * Gets the value of the firstdate property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getFirstdate() {
            return firstdate;
        }

        /**
         * Sets the value of the firstdate property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setFirstdate(String value) {
            this.firstdate = value;
        }

        /**
         * Gets the value of the firstdatetaken property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getFirstdatetaken() {
            return firstdatetaken;
        }

        /**
         * Sets the value of the firstdatetaken property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setFirstdatetaken(String value) {
            this.firstdatetaken = value;
        }

        /**
         * Gets the value of the count property.
         * 
         */
        public int getCount() {
            return count;
        }

        /**
         * Sets the value of the count property.
         * 
         */
        public void setCount(int value) {
            this.count = value;
        }

    }

}
